#!/bin/sh

playing="$(mpc | grep playing | cut -c 2-8)"
paused="$(mpc | grep paused | cut -c 2-7)"

if [ "$playing" = "playing" ]; then

  longtext="$(mpc current)"
  echo "$longtext"

  shorttext="$(mpc current -f %title%)"
	echo "$shorttext"

  # color
  echo ""
	exit 0
fi

if [ "$paused" = "paused" ]; then

  longtext="$(mpc current)"
  echo "$longtext"

  shorttext="$(mpc current -f %title%)"
	echo "$shorttext"

  # color
  echo ""
	exit 0
fi

echo ""
echo ""
echo "#FFFFCC"

